version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: air-nginx-openresty
    networks:
      - air-network
    ports:
      - "7000:7000"
    volumes:
      - ./static_public:/usr/share/nginx/static_public:ro
      - ./logs:/var/log/nginx
    restart: unless-stopped

networks:
  air-network:
    external: true