version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: air-nginx-openresty
    network_mode: host
    volumes:
      - ./static_public:/usr/share/nginx/static_public:ro
      - ./logs:/var/log/nginx
    restart: unless-stopped
