version: '3.8'

services:
  nginx:
    build: .
    container_name: air-nginx
    network_mode: host
    volumes:
      - ./static:/usr/share/nginx/static  # монтирование статики
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s